steps:

- id: "Rodando testes"
  name: 'gcr.io/cloud-builders/go'
  args:
  - 'test'
  - './src'

- id: "Building image from Dockerfile.prod"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA'
  - '-f'
  - 'Dockerfile.prod'
  - '.'


- id: "Pushing image"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA'

- id: "Adjusting deployment file k8s"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    sed 's#img-gohpa-deployment#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' deployment.yaml > deployment_new.yaml;


- id: "Deployment k8s"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'deployment_new.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'
