apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 3
  selector:
      matchLabels:
        app: go-hpa
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: c-go-hpa
        image: jonatasrafael/go-hpa
        ports:
        - containerPort: 8000
